{% set name = "requests-gracedb" %}
{% set version = "0.1.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: a9304406912754b03834217d686d233f975b6c3206b6ada8b44f73d951999248

build:
  noarch: python
  number: 1
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools >=61
    - setuptools-scm >=6.2
  run:
    - cryptography
    - python >={{ python_min }}
    - requests
    - safe-netrc

test:
  requires:
    - pip
    - pytest
    - pytest-freezegun
    - pytest-httpserver
    - pytest-socket
    - python {{ python_min }}
  commands:
    # check metadata
    - python -m pip check requests-gracedb
    - python -m pip show requests-gracedb
    # run test suite
    - python -m pytest --pyargs requests_gracedb

about:
  description: |
    requests-gracedb provides a generic REST API client for GraceDB and similar
    LIGO/Virgo API services. It uses the powerful Requests package for reliable
    and high-throughput HTTP connection pooling.
  dev_url: https://git.ligo.org/emfollow/requests-gracedb
  doc_url: https://requests-gracedb.readthedocs.io/
  home: https://git.ligo.org/emfollow/requests-gracedb
  license: GPL-2.0-or-later
  license_family: GPL
  license_file: LICENSE.md
  summary: generic connection pooling HTTP client for GraceDB and similar services

extra:
  recipe-maintainers:
    - duncanmmacleod
