{% set name = "requests-gracedb" %}
{% set version = "0.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name | replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 3e6e929ed230d4ff109b7f181760c3b4a43e3bd718d8e2f6f427e6c439638cc3

build:
  noarch: python
  number: 1
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools >=77
    - setuptools-scm >=8
  run:
    - cryptography >=42
    - igwn-auth-utils >=1.3.0
    - pyjwt
    - python >={{ python_min }}
    - requests
    - safe-netrc

test:
  requires:
    - pip
    - pytest
    - pytest-freezegun
    - pytest-httpserver
    - pytest-socket
    - python {{ python_min }}
  commands:
    # check metadata
    - python -m pip check requests-gracedb
    - python -m pip show requests-gracedb
    # run test suite
    - python -m pytest --pyargs requests_gracedb

about:
  description: |
    requests-gracedb provides a generic REST API client for GraceDB and similar
    LIGO/Virgo API services. It uses the powerful Requests package for reliable
    and high-throughput HTTP connection pooling.
  dev_url: https://git.ligo.org/emfollow/requests-gracedb
  doc_url: https://requests-gracedb.readthedocs.io/
  home: https://git.ligo.org/emfollow/requests-gracedb
  license: GPL-2.0-or-later
  license_family: GPL
  license_file: LICENSE.md
  summary: generic connection pooling HTTP client for GraceDB and similar services

extra:
  recipe-maintainers:
    - duncanmmacleod
