{% set name = "requests-gracedb" %}
{% set version = "0.1.1" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: "https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz"
  sha256: afa25548c657744c839702051aaed32df2c8e0122d619d5a6dc3f744ce1e32ac

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv "

requirements:
  host:
    - pip
    - python
    - setuptools >=38.3.0
  run:
    - cryptography
    - python
    - requests
    - safe-netrc
    - six

test:
  imports:
    - requests_gracedb
  requires:
    - pytest
    - pytest-freezegun
    - pytest-httpserver
    - pytest-socket
    - python >=3
  commands:
    - python -m pytest --pyargs requests_gracedb

about:
  description: |
    requests-gracedb provides a generic REST API client for GraceDB and similar
    LIGO/Virgo API services. It uses the powerful Requests package for reliable
    and high-throughput HTTP connection pooling.
  dev_url: "https://git.ligo.org/emfollow/requests-gracedb"
  doc_url: "https://requests-gracedb.readthedocs.io/"
  home: "https://git.ligo.org/emfollow/requests-gracedb"
  license: "GPL-2.0-or-later"
  license_family: "GPL"
  license_file: "LICENSE.rst"
  summary: "generic connection pooling HTTP client for GraceDB and similar services"

extra:
  recipe-maintainers:
    - duncanmmacleod
